# Generated by Django 3.2.16 on 2023-02-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo__app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1992-12-12'),
            preserve_default=False,
        ),
    ]
